import { useEffect, useMemo, useState } from 'react'
import { AlertTriangle, BarChart3, Check, Database, ExternalLink, FileUp, Layers3, Plus, ReceiptText, ShieldCheck, Trash2 } from 'lucide-react'
import { migratePlan, type AssetClass, type Holding, type PortfolioTransaction, type WealthPlan } from '../domain/schema'
import { analyzePortfolio, assetClassLabels, buildRebalancePreview, parseCsv, type CsvMapping, validateCsvImport } from '../domain/portfolio'
import { PortfolioAccounts } from './PortfolioAccounts'
import { FormattedNumberInput } from './FormattedNumberInput'

const money = new Intl.NumberFormat('th-TH', { style: 'currency', currency: 'THB', maximumFractionDigits: 0 })
const percent = (value: number) => `${value.toFixed(1)}%`
const assetClasses = Object.keys(assetClassLabels) as AssetClass[]
const defaultMapping: CsvMapping = { externalId: 'id', accountId: 'account', symbol: 'symbol', type: 'type', date: 'date', quantity: 'quantity', price: 'price', amount: 'amount', currency: 'currency', fxToThb: 'fx' }

function ExposureList({ title, rows }: { title: string; rows: Array<{ name: string; weight: number }> }) {
  return <article className="exposure-card"><strong>{title}</strong>{rows.slice(0, 6).map((row) => <div key={row.name}><span>{row.name}</span><i><b style={{ width: `${Math.min(100, row.weight)}%` }} /></i><em>{percent(row.weight)}</em></div>)}</article>
}

export function PortfolioStudio({ plan: rawPlan, setPlan }: { plan: WealthPlan; setPlan: React.Dispatch<React.SetStateAction<WealthPlan>> }) {
  const plan = Array.isArray(rawPlan.holdings) ? rawPlan : migratePlan(rawPlan)
  useEffect(() => { if (!Array.isArray(rawPlan.holdings)) setPlan(migratePlan(rawPlan)) }, [rawPlan, setPlan])
  const analysis = useMemo(() => analyzePortfolio(plan), [plan])
  const preview = useMemo(() => buildRebalancePreview(plan), [plan])
  const [csvText, setCsvText] = useState('id,account,symbol,type,date,quantity,price,amount,currency,fx\nNEW-001,portfolio-thai,K-SET50,buy,2026-08-06,100,16.5,1650,THB,1')
  const [mapping, setMapping] = useState<CsvMapping>(defaultMapping)
  const [showValidation, setShowValidation] = useState(false)
  const validation = useMemo(() => validateCsvImport(csvText, mapping, plan), [csvText, mapping, plan])
  const headers = useMemo(() => { try { return parseCsv(csvText)[0] ?? [] } catch { return [] } }, [csvText])
  const patchHolding = (id: string, patch: Partial<Holding>) => {
    const resetsMarketProvenance = ['currentPrice', 'fxToThb', 'annualFee', 'dividendYield'].some((field) => field in patch)
    const now = new Date().toISOString()
    const manualProvenance: Partial<Holding> = resetsMarketProvenance ? { source: 'ผู้ใช้กรอกเอง', sourceProvider: 'user-input', sourceUrl: null, sourceAsOf: now.slice(0, 10), sourceFetchedAt: now, sourceStaleAfterHours: 24 * 90, sourceLicensingStatus: 'userAuthorized', sourceConfidence: 'userProvided', sourceValidationStatus: 'valid' } : {}
    setPlan((current) => ({ ...current, holdings: current.holdings.map((holding) => holding.id === id ? { ...holding, ...patch, ...manualProvenance } : holding), investmentPolicy: { ...current.investmentPolicy, approvalStatus: 'draft', approvedAt: null } }))
  }
  const patchTransaction = (id: string, patch: Partial<PortfolioTransaction>) => setPlan((current) => ({ ...current, transactions: current.transactions.map((tx) => tx.id === id ? { ...tx, ...patch } : tx) }))
  const addHolding = () => setPlan((current) => { const now = new Date().toISOString(); return { ...current, holdings: [...current.holdings, { id: crypto.randomUUID(), accountId: current.portfolioAccounts[0]?.id ?? 'portfolio-thai', symbol: 'NEW', name: 'สินทรัพย์ใหม่', assetClass: 'other', quantity: 0, currentPrice: 0, costBasisPerUnit: 0, currency: 'THB', fxToThb: 1, annualFee: 0, dividendYield: 0, volatility: 10, maxDrawdown: 20, durationYears: null, creditQuality: null, fxHedgedPercent: 100, geography: [{ name: 'ไม่ระบุ', weight: 100 }], sector: [{ name: 'ไม่ระบุ', weight: 100 }], currencyExposure: [{ name: 'THB', weight: 100 }], factor: [{ name: 'ไม่ระบุ', weight: 100 }], underlying: [], source: 'ผู้ใช้กรอกเอง', sourceProvider: 'user-input', sourceUrl: null, sourceAsOf: now.slice(0, 10), sourceFetchedAt: now, sourceStaleAfterHours: 24 * 90, sourceLicensingStatus: 'userAuthorized', sourceConfidence: 'userProvided', sourceValidationStatus: 'valid' }] } })
  const addTransaction = () => setPlan((current) => ({ ...current, transactions: [...current.transactions, { id: crypto.randomUUID(), externalId: null, accountId: current.portfolioAccounts[0]?.id ?? 'portfolio-thai', holdingId: current.holdings[0]?.id ?? null, type: 'buy', date: new Date().toISOString().slice(0, 10), quantity: 0, price: 0, amount: 0, currency: 'THB', fxToThb: 1, sourceRow: null, notes: 'ผู้ใช้เพิ่มเอง' }] }))
  const importValid = () => {
    if (!validation.valid.length) return
    setPlan((current) => ({ ...current, transactions: [...current.transactions, ...validation.valid.map((row) => row.candidate)] }))
    setShowValidation(true)
  }

  return <section className="content-section portfolio-studio" id="portfolio">
    <div className="section-heading"><div><span className="eyebrow">PORTFOLIO X-RAY</span><h2>เห็นความเสี่ยงจริงใต้ชื่อกองทุน</h2></div><span className="preview-boundary"><ShieldCheck />วิเคราะห์และ preview เท่านั้น · ไม่มีระบบส่งคำสั่งซื้อขาย</span></div>
    <div className="portfolio-summary">
      <article className="portfolio-hero"><span>มูลค่าพอร์ตรวม</span><strong>{money.format(analysis.totalValue)}</strong><small>ต้นทุน {money.format(analysis.totalCost)} · ตรวจจาก {plan.holdings.length} holdings</small></article>
      <article><span>Unrealized</span><strong className={analysis.unrealizedReturn >= 0 ? 'positive' : 'negative'}>{money.format(analysis.unrealizedReturn)}</strong><small>Realized {money.format(analysis.realizedReturn)}</small></article>
      <article><span>ผลตอบแทนรวม</span><strong>{percent(analysis.periodReturn)}</strong><small>เทียบ {plan.benchmark.symbol}: {analysis.benchmarkDifference >= 0 ? '+' : ''}{percent(analysis.benchmarkDifference)}</small></article>
      <article><span>ปันผลที่บันทึกแล้ว</span><strong>{money.format(analysis.dividendIncome)}</strong><small>income yield จำลอง {percent(analysis.incomeYield)}</small></article>
      <article><span>ค่าธรรมเนียมกองทุน/ปี</span><strong>{money.format(analysis.annualFeeBaht)}</strong><small>weighted fee {percent(analysis.feeRate)}</small></article>
      <article><span>FX ไม่ hedge</span><strong>{percent(analysis.unhedgedFxWeight)}</strong><small>{money.format(analysis.unhedgedFxValue)}</small></article>
    </div>

    <PortfolioAccounts plan={plan} setPlan={setPlan} />

    <details className="panel portfolio-data-register"><summary><span><Database /><b>Market data provenance</b></span><small>{plan.holdings.length} holdings · ไม่มีค่าใดถูกเรียกว่า latest โดยไม่มีวันที่</small></summary><div>{plan.holdings.map((holding) => { const ageHours = Math.max(0, (Date.now() - Date.parse(holding.sourceAsOf)) / 3_600_000); const stale = ageHours > holding.sourceStaleAfterHours; return <article key={holding.id}><span><strong>{holding.symbol}</strong><small>{holding.sourceProvider} · as of {holding.sourceAsOf}</small></span><span><b className={stale ? 'stale' : 'current'}>{stale ? 'stale snapshot' : 'dated snapshot'}</b><small>{holding.sourceLicensingStatus} · {holding.sourceConfidence} · {holding.sourceValidationStatus}</small></span><span><small>Fetched</small><b>{holding.sourceFetchedAt ?? 'ผู้ใช้กรอก · ไม่มี retrieval time'}</b></span>{holding.sourceUrl ? <a href={holding.sourceUrl} target="_blank" rel="noreferrer">Source<ExternalLink /></a> : <em>ไม่มี source URL · user input</em>}</article> })}</div></details>

    <div className="xray-grid">
      <article className="panel holdings-card"><div className="portfolio-card-head"><div><Database /><span><b>Holdings & Cost Basis</b><small>{analysis.ledger.reconciliation.filter((row) => Math.abs(row.difference) > .0001).length} รายการยอดไม่ตรง ledger</small></span></div><button onClick={addHolding}><Plus />เพิ่ม holding</button></div><div className="holdings-table">{analysis.holdings.map((row) => <details key={row.holding.id}><summary><span><b>{row.holding.symbol}</b><small>{row.holding.name}</small></span><em>{assetClassLabels[row.holding.assetClass]}</em><strong>{money.format(row.value)}</strong><i>{percent(row.weight)}</i></summary><div className="holding-editor"><label>จำนวน<FormattedNumberInput min="0" value={row.holding.quantity} onValueChange={(value) => patchHolding(row.holding.id, { quantity: Math.max(0, value) })} /></label><label>ราคาปัจจุบัน<FormattedNumberInput min="0" step="0.01" value={row.holding.currentPrice} onValueChange={(value) => patchHolding(row.holding.id, { currentPrice: Math.max(0, value) })} /></label><label>ต้นทุน/หน่วย<FormattedNumberInput min="0" step="0.01" value={row.holding.costBasisPerUnit} onValueChange={(value) => patchHolding(row.holding.id, { costBasisPerUnit: Math.max(0, value) })} /></label><label>FX→THB<FormattedNumberInput min="0.0001" step="0.01" value={row.holding.fxToThb} onValueChange={(value) => patchHolding(row.holding.id, { fxToThb: Math.max(.0001, value) })} /></label><label>ค่าธรรมเนียม %<FormattedNumberInput min="0" step="0.01" value={row.holding.annualFee} onValueChange={(value) => patchHolding(row.holding.id, { annualFee: Math.max(0, value) })} /></label><label>ปันผล %<FormattedNumberInput min="0" step="0.1" value={row.holding.dividendYield} onValueChange={(value) => patchHolding(row.holding.id, { dividendYield: Math.max(0, value) })} /></label><label>Asset class<select value={row.holding.assetClass} onChange={(event) => patchHolding(row.holding.id, { assetClass: event.target.value as AssetClass })}>{assetClasses.map((assetClass) => <option value={assetClass} key={assetClass}>{assetClassLabels[assetClass]}</option>)}</select></label><label>FX hedge %<FormattedNumberInput min="0" max="100" value={row.holding.fxHedgedPercent} onValueChange={(value) => patchHolding(row.holding.id, { fxHedgedPercent: Math.max(0, Math.min(100, value)) })} /></label><p><b>Provenance</b>{row.holding.source} · as of {row.holding.sourceAsOf}<br />Unrealized {money.format(row.unrealized)} · risk contribution {percent(analysis.riskContribution.find((risk) => risk.symbol === row.holding.symbol)?.contribution ?? 0)}</p><button aria-label={`ลบ ${row.holding.symbol}`} onClick={() => setPlan((current) => ({ ...current, holdings: current.holdings.filter((holding) => holding.id !== row.holding.id), transactions: current.transactions.filter((tx) => tx.holdingId !== row.holding.id) }))}><Trash2 />ลบ holding และรายการที่ผูกอยู่</button></div></details>)}</div></article>
      <article className="panel risk-card"><div className="portfolio-card-head"><div><BarChart3 /><span><b>Risk Lens</b><small>metric จากข้อมูลที่กรอก ไม่ใช่ forecast</small></span></div></div><div className="risk-metrics"><div><span>Volatility proxy</span><strong>{percent(analysis.weightedVolatility)}</strong></div><div><span>Drawdown proxy</span><strong>-{percent(analysis.weightedDrawdown)}</strong></div><div><span>Concentration HHI</span><strong>{analysis.concentrationHhi.toFixed(0)}</strong></div><div><span>Bond duration</span><strong>{analysis.durationYears === null ? 'ไม่มีข้อมูล' : `${analysis.durationYears.toFixed(1)} ปี`}</strong></div></div><div className="risk-list"><strong>Risk contribution</strong>{analysis.riskContribution.slice(0, 5).map((row) => <div key={row.symbol}><span>{row.symbol}</span><i><b style={{ width: `${row.contribution}%` }} /></i><em>{percent(row.contribution)}</em></div>)}</div><div className="correlation-list"><strong>Correlation proxy สูงสุด</strong>{analysis.correlations.slice(0, 3).map((row) => <p key={`${row.left}-${row.right}`}><b>{row.left} ↔ {row.right}</b><span>{row.proxy.toFixed(2)} · {row.reason}</span></p>)}</div></article>
    </div>

    <div className="exposure-grid" role="region" aria-label="สัดส่วนพอร์ตแยกตามมุมมอง เลื่อนแนวนอนได้" tabIndex={0}><ExposureList title="Asset class" rows={analysis.assetAllocation.map((row) => ({ name: row.label, weight: row.weight }))} /><ExposureList title="ประเทศ/ภูมิภาค" rows={analysis.geography} /><ExposureList title="Sector" rows={analysis.sector} /><ExposureList title="Currency" rows={analysis.currency} /><ExposureList title="Factor / Theme" rows={analysis.factor} /></div>
    <div className="overlap-strip panel"><div><Layers3 /><span><b>Fund look-through & overlap</b><small>{analysis.overlap.length ? `พบสินทรัพย์ย่อยซ้ำ ${analysis.overlap.length} รายการ` : 'ไม่พบ overlap จากข้อมูลที่มี'}</small></span></div>{analysis.overlap.map((item) => <article key={item.symbol}><strong>{item.symbol}</strong><span>{item.funds.join(' + ')}</span><em>{percent(item.portfolioWeight)} ของพอร์ต</em></article>)}{!analysis.overlap.length && <p>เพิ่ม underlying holdings เพื่อให้ระบบตรวจ overlap ได้ละเอียดขึ้น</p>}</div>

    <div className="policy-import-grid">
      <article className="panel policy-card"><div className="portfolio-card-head"><div><ShieldCheck /><span><b>Investment Policy Studio</b><small>เป้าหมาย สัดส่วน และ rebalance band</small></span></div><select aria-label="ระดับความเสี่ยงของ Investment Policy" value={plan.investmentPolicy.riskProfile} onChange={(event) => setPlan((current) => ({ ...current, investmentPolicy: { ...current.investmentPolicy, riskProfile: event.target.value as 'conservative' | 'balanced' | 'growth', approvalStatus: 'draft', approvedAt: null } }))}><option value="conservative">Conservative</option><option value="balanced">Balanced</option><option value="growth">Growth</option></select></div><div className="policy-controls"><label>Max single holding %<FormattedNumberInput min="1" max="100" value={plan.investmentPolicy.maxSingleHolding} onValueChange={(value) => setPlan((current) => ({ ...current, investmentPolicy: { ...current.investmentPolicy, maxSingleHolding: value, approvalStatus: 'draft', approvedAt: null } }))} /></label><label>Rebalance band ±%<FormattedNumberInput min="0" max="50" value={plan.investmentPolicy.rebalanceBand} onValueChange={(value) => setPlan((current) => ({ ...current, investmentPolicy: { ...current.investmentPolicy, rebalanceBand: value, approvalStatus: 'draft', approvedAt: null } }))} /></label></div><div className="target-list">{plan.investmentPolicy.targets.map((target) => <div key={target.assetClass}><span>{assetClassLabels[target.assetClass]}</span><FormattedNumberInput aria-label={`เป้าหมาย ${assetClassLabels[target.assetClass]}`} min="0" max="100" value={target.targetWeight} onValueChange={(value) => setPlan((current) => ({ ...current, investmentPolicy: { ...current.investmentPolicy, targets: current.investmentPolicy.targets.map((row) => row.assetClass === target.assetClass ? { ...row, targetWeight: value } : row), approvalStatus: 'draft', approvedAt: null } }))} /><em>%</em></div>)}</div><div className="rebalance-preview"><strong>Preview ที่อยู่นอก band</strong>{preview.filter((row) => row.outsideBand).map((row) => <p key={row.assetClass}><span>{row.label}<small>{percent(row.currentWeight)} → {percent(row.targetWeight)}</small></span><b className={row.action}>{row.action === 'buy' ? 'เพิ่ม' : 'ลด'} {money.format(Math.abs(row.amount))}</b></p>)}</div><button className={`approve-preview ${plan.investmentPolicy.approvalStatus}`} onClick={() => setPlan((current) => ({ ...current, investmentPolicy: { ...current.investmentPolicy, approvalStatus: current.investmentPolicy.approvalStatus === 'draft' ? 'approved' : 'draft', approvedAt: current.investmentPolicy.approvalStatus === 'draft' ? new Date().toISOString() : null } }))}>{plan.investmentPolicy.approvalStatus === 'approved' ? <><Check />อนุมัติ preview แล้ว · ยังไม่มีคำสั่งซื้อขาย</> : <><ShieldCheck />ตรวจและอนุมัติแผน preview</>}</button></article>
      <article className="panel import-card"><div className="portfolio-card-head"><div><FileUp /><span><b>CSV Import Lab</b><small>map → validate → แก้เอง → import</small></span></div><button onClick={() => setShowValidation(true)}>ตรวจไฟล์</button></div><textarea aria-label="ข้อมูล CSV สำหรับนำเข้า" value={csvText} onChange={(event) => { setCsvText(event.target.value); setShowValidation(false) }} /><details><summary>ตั้งค่า column mapping</summary><div className="mapping-grid">{(Object.keys(mapping) as Array<keyof CsvMapping>).map((field) => <label key={field}>{field}<select value={mapping[field]} onChange={(event) => setMapping((current) => ({ ...current, [field]: event.target.value }))}>{headers.map((header) => <option value={header} key={header}>{header}</option>)}</select></label>)}</div></details>{showValidation && <div className="validation-report"><div><span className="valid">พร้อม {validation.valid.length}</span><span className="duplicate">ซ้ำ {validation.duplicates.length}</span><span className="invalid">ผิด {validation.invalid.length}</span></div>{validation.rows.map((row) => <p key={row.row} className={row.duplicate ? 'duplicate' : row.issues.length ? 'invalid' : 'valid'}><b>แถว {row.row}</b><span>{row.duplicate ? 'ข้อมูลซ้ำ — ไม่ import' : row.issues.length ? row.issues.join(' · ') : `${row.candidate.type} ${row.candidate.holdingId ?? 'fee'}`}</span></p>)}</div>}<p className="manual-note"><AlertTriangle />ระบบไม่แก้ข้อมูลต้นฉบับเงียบ ๆ: แก้ค่าใน staging ด้านบน แล้วกดตรวจใหม่</p><button className="import-valid" disabled={!validation.valid.length} onClick={importValid}><ReceiptText />Import เฉพาะ {validation.valid.length} แถวที่ผ่าน</button></article>
    </div>

    <div className="recommendation-trace panel"><strong>Recommendation trace</strong>{preview.filter((row) => row.outsideBand).map((row) => <article key={row.assetClass}><span><b>{row.label}</b>{row.action === 'buy' ? 'เพิ่ม' : 'ลด'} {money.format(Math.abs(row.amount))}</span><small>{row.contributors.map((item) => `${item.symbol} · ${item.source} · ${item.sourceAsOf}`).join(' | ')}</small></article>)}</div>

    <article className="panel transaction-card"><div className="portfolio-card-head"><div><ReceiptText /><span><b>Transaction Ledger</b><small>average-cost convention · duplicate {analysis.ledger.duplicates.length} · issue {analysis.ledger.issues.length}</small></span></div><button onClick={addTransaction}><Plus />เพิ่มรายการ</button></div><div className="transaction-table">{plan.transactions.slice(-12).reverse().map((tx) => <div key={tx.id}><input aria-label="วันที่รายการ" type="date" value={tx.date} onChange={(event) => patchTransaction(tx.id, { date: event.target.value })} /><select aria-label="ประเภทรายการ" value={tx.type} onChange={(event) => patchTransaction(tx.id, { type: event.target.value as PortfolioTransaction['type'] })}><option value="buy">Buy</option><option value="sell">Sell</option><option value="dividend">Dividend</option><option value="split">Split</option><option value="fee">Fee</option></select><select aria-label="holding ของรายการ" value={tx.holdingId ?? ''} onChange={(event) => patchTransaction(tx.id, { holdingId: event.target.value || null })}><option value="">ไม่ผูก holding</option>{plan.holdings.map((holding) => <option value={holding.id} key={holding.id}>{holding.symbol}</option>)}</select><FormattedNumberInput aria-label="จำนวนหน่วย" value={tx.quantity} onValueChange={(value) => patchTransaction(tx.id, { quantity: value })} /><FormattedNumberInput aria-label="ราคา" value={tx.price} onValueChange={(value) => patchTransaction(tx.id, { price: value })} /><FormattedNumberInput aria-label="FX" min="0.0001" value={tx.fxToThb} onValueChange={(value) => patchTransaction(tx.id, { fxToThb: Math.max(.0001, value) })} /><button aria-label="ลบรายการ" onClick={() => setPlan((current) => ({ ...current, transactions: current.transactions.filter((row) => row.id !== tx.id) }))}><Trash2 /></button></div>)}</div></article>
  </section>
}
